spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:apex
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
jwt.secret=4D6E5A6F72617468414E4F544845524B6F6E67456E6B69656E7267656E45754F





spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1/chat/completions
spring.ai.openai.chat.options.model=nvidia/nemotron-3-super-120b-a12b:free
