spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:apex
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
openrouter.api.key=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
jwt.secret=abcdefghijklmnopqrstuvwxyz123456